#Whether progression tags should be used for mob spawning
enableProgression = true
#Whether a fix should be applied to stop mob pathfinding from being biased towards higher locations
fixLandRandomPos = true
