		[types.stone_type.aether]
			holystone = true

		[types.stone_type.architects_palette]
			abyssaline = true
			hadaline = true
			myonite = true
			esoterrack = true
			onyx = true
			wardstone = true
			moonshale = true
			nebulite = true

		[types.stone_type.atmospheric]
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true

		[types.stone_type.botania]
			livingrock = true
			fuchsite = true
			talc = true
			gneiss = true
			mycelite = true
			cataclasite = true
			solite = true
			lunite = true

		[types.stone_type.bountifulfares]
			feldspar = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true
			cylindrite = true
			cassiterite = true
			rhyolite = true

		[types.stone_type.create]
			limestone = false
			asurine = false
			crimsite = false
			ochrum = false
			veridium = false
			scoria = false
			scorchia = false

		[types.stone_type.darkerdepths]
			aridrock = true
			duskrock = true
			darkslate = true
			grimestone = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.naturalist]
			shellstone = true

		[types.stone_type.nomansland]
			silt = true
			siltstone = true

		[types.stone_type.oreganized]
			glance = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = false
			jasper = false
			shale = false
			myalite = true
			permafrost = true

		[types.stone_type.supplementaries]
			brittlestone = true

		[types.stone_type.twigs]
			schist = true
			rhyolite = true
			bloodstone = true

		[types.stone_type.twilightforest]
			deadrock = false
			mazestone = false

		[types.wood_type.abundant_atmosphere]
			red_bamboo = true
			ashroot = true
			gourdrot = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.autumnity]
			maple = false

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.bountifulfares]
			hoary = true
			walnut = false

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.eidolon_repraised]
			illwood = true

		[types.wood_type.environmental]
			willow = false
			pine = false
			plum = true
			wisteria = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.quark]
			azalea = false
			ancient = false
			blossom = false

		[types.wood_type.soulfulnether]
			fright = true

		[types.wood_type.spawn]
			rotten = true
			date = true

		[types.wood_type.twilightforest]
			twilight_oak = false
			canopy = false
			mangrove = false
			dark = false
			time = false
			transformation = false
			mining = false
			sorting = false

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.cake.bountifulfares]
			coconut_cake = false
			cocoa_cake = false
			sponge_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.lantern.architects_palette]
			nether_brass_lantern = true

		[types.lantern.bountifulfares]
			feldspar_lantern = true

		[types.lantern.caverns_and_chasms]
			cupric_lantern = true
			copper_lantern = true
			exposed_copper_lantern = true
			weathered_copper_lantern = true
			oxidized_copper_lantern = true
			waxed_copper_lantern = true
			waxed_exposed_copper_lantern = true
			waxed_weathered_copper_lantern = true
			waxed_oxidized_copper_lantern = true

		[types.lantern.darkerdepths]
			glowshroom_lantern = true

		[types.lantern.netherexp]
			ancient_lantern = true

		[types.lantern.twigs]
			paper_lantern = true
			allium_paper_lantern = true
			blue_orchid_paper_lantern = true
			crimson_roots_paper_lantern = true
			dandelion_paper_lantern = true
			torchflower_paper_lantern = true

		[types.lantern.remix_core]
			caelic_lantern = true

		[types.leaves_type.abundant_atmosphere]
			ashroot = true
			gourdrot = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.bountifulfares]
			apple = true
			flowering_apple = true
			orange = true
			flowering_orange = true
			lemon = true
			flowering_lemon = true
			plum = true
			flowering_plum = true
			hoary = true
			walnut = true
			golden_apple = true
			flowering_golden_apple = true

		[types.leaves_type.eidolon_repraised]
			illwood = true

		[types.leaves_type.environmental]
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true

		[types.leaves_type.galosphere]
			opal = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.nomansland]
			autumnal_oak = true
			frosted = true
			pale_cherry = true
			red_maple = true
			yellow_birch = true
			pine = true
			maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.remix_core]
			dead = true
			aspen = true
			birch = true
			pear = true
			flowering_pear = true

		[types.leaves_type.spawn]
			date = true

		[types.leaves_type.twilightforest]
			thorn = false
			beanstalk = false
			twilight_oak = false
			canopy = false
			mangrove = false
			dark = false
			rainbow_oak = false
			time = false
			transformation = false
			mining = false
			sorting = false

		[types.leaves_type.upgrade_aquatic]
			river = true

		[entries.stone_type.create]
			small_brick_wall = false
			cut_wall = false
			small_bricks = false
			cut_brick_slab = false
			polished_cut_slab = false
			small_brick_stairs = false
			cut_bricks = false
			cut = false
			polished_cut = false
			small_brick_slab = false
			layered = false
			polished_cut_stairs = false
			cut_brick_wall = false
			pillar = false
			cut_stairs = false
			cut_brick_stairs = false
			polished_cut_wall = false
			cut_slab = false

		[entries.stone_type.quark]
			polished_vertical_slab = false
			pillar = false
			vertical_slab = false

		[entries.stone_type.twigs]
			column = true

		[entries.mud_type.quark]
			carved_bricks = false
			pillar = false
			brick_lattice = false

		[entries.wood_type.another_furniture]
			flower_box = false
			shelf = true
			shutter = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.bountifulfares]
			trellis = true
			pickets = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.nomansland]
			bookshelf = false
			trimmed_planks = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = false
			post = true
			trapped_chest = false
			bookshelf = false
			chest = false
			stripped_post = true
			ladder = false
			vertical_slab = false

		[entries.wood_type.twigs]
			table = false

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = false

		[entries.leaves_type.woodworks]
			leaf_pile = true
