// priority: 100

/** 
 * @import {$ItemModificationKubeEvent} "dev.latvian.mods.kubejs.item.ItemModificationKubeEvent" 
*/

global.WOOD_TYPES = {}
global.DISABLED_WOOD_TYPES = {}
global.ITEM_SWAPPER = new Map()
global.BLOCK_SWAPPER = new Map()
global.ENTITY_SWAPPER = new Map()
global.STRUCTURE_BLOCK_SWAPPER = new Map()
global.STATE_SWAPPER = []
global.COMMON_SWAPPER = new Map()  // items and blocks combined
global.BLOCKSWAP_CONFIG = {
    __comment: 'This config was autogenerated from starter_scripts/_core/block_swap.js',
    generate_all_known_states: false,
    retro_gen: false,
    state_swapper: [],
    swapper: new Map()  // becomes an Object after processBlockswapConfig()
}
global.ENTITY_REMOVALS = []
global.REMOVALS = {
    set: new Set(),
    arr: [],
    items: new Set(),
    blocks: new Set(),
    add: function (entry) {
        if (entry != undefined) {
            if (entry instanceof Array) {
                // Filters out undefined elements
                for (const elem of entry) this.add(elem)
            } else if (entry.constructor === Object) {
                // Add all strings in an object and any nested objects
                this.add(collectStrings(entry))
            } else if (entry instanceof RegExp) {
                this.add(Ingredient.of(entry).itemIds.toArray())
                if (global.DEBUG_MODE) console.log(`"${entry}" has matched: ${Ingredient.of(entry).itemIds}`)
            } else {
                if (Item.exists(entry)) {
                    if (!this.set.has(entry)) this.arr.push(entry)
                    this.set.add(entry)
                    if (Item.of(entry).getBlock() != null) this.blocks.add(entry)
                    else this.items.add(entry)
                } else {
                    console.error(`Removal: "${entry}" doesn't exist!`)
                }
            }
        } else {
            console.error('Cant remove undefined!')
        }
    }
}
global.DEBUG_MODE = false
global.COLOURS = [
    'white',
    'orange',
    'magenta',
    'light_blue',
    'yellow',
    'lime',
    'pink',
    'gray',
    'light_gray',
    'cyan',
    'purple',
    'blue',
    'brown',
    'green',
    'red',
    'black'
]

/**
 * Convert a non-JS JSON Object to a JS Object
 * @param {*} json - the weird built in JSON thing
 * @returns {Object} JS Object
 */
global.json2json = (json) => JSON.parse(JsonIO.toString(json))

global.readJson = (mod, location, type) => {
    if (type == undefined) return global.json2json(KJSTweaks.readJsonFromMod(mod, location))
    else return global.json2json(KJSTweaks.readJsonFromMod(mod, location, type))
}

// Collect all strings in a nested object with recursion
function collectStrings(obj) {
    const result = []

    const recurse = (value) => {
        if (typeof value === "string") {
            result.push(value)
        } else if (value && typeof value === "object") {
            for (const key in value) {
                recurse(value[key])
            }
        }
    }

    recurse(obj);
    return result;
}

/**
 * Swap a constructed woodType with another
 * @param {Object} woodTypeFrom - ex: `global.DISABLED_WOOD_TYPES.mod.woodType`
 * @param {Object} woodTypeTo - ex: `global.WOOD_TYPES.mod.woodType`
 */
function swapWoodType(woodTypeFrom, woodTypeTo) {
    Object.keys(woodTypeFrom).forEach(entry => {
        Object.keys(woodTypeFrom[entry]).forEach(woodenBlock => {
            if (woodTypeFrom[entry][woodenBlock] != undefined && woodTypeTo[entry][woodenBlock] != undefined) {
                global.BLOCK_SWAPPER.set(woodTypeFrom[entry][woodenBlock], woodTypeTo[entry][woodenBlock])
            }
        })
    })
}

/**
 * Replace vanilla chest with new chest in a structure
 * @param {String} structure - Structure ID or tag
 * @param {String} woodType - The woodtype (mod:type)
 */
function structureSwapChest(structure, woodType) {
    const woodTypeSplit = woodType.split(':')
    const mod = woodTypeSplit[0];
    const type = woodTypeSplit[1]
    global.STRUCTURE_BLOCK_SWAPPER.set(structure, new Map([
        ['minecraft:chest', global.WOOD_TYPES[mod][type].woodworks.chest],
        ['minecraft:trapped_chest', global.WOOD_TYPES[mod][type].woodworks.trapped_chest],
    ]))
}

// maybe in the future I could construct this from the everycomp config
const woodTypesToConstruct = {
    minecraft: {
        oak: true,
        spruce: true,
        birch: true,
        jungle: true,
        dark_oak: true,
        acacia: true,
        mangrove: true,
        bamboo: true,
        cherry: true,
        crimson: true,
        warped: true,
        // pale_oak: false,  // vanilla backport's mod id changed
    },
    dungeonsdelight: {
        wormwood: true
    },
    caverns_and_chasms: {
        azalea: true,
    },
    darkerdepths: {
        petrified: true,
    },
    quark: {
        azalea: false,
        ancient: false,
        blossom: false,
    },
    cobblemon: {
        apricorn: true,
        saccharine: true,
    },
    pastel: {
        black: true,
        blue: true,
        brown: true,
        cyan: true,
        gray: true,
        green: true,
        light_blue: true,
        light_gray: true,
        lime: true,
        magenta: true,
        orange: true,
        pink: true,
        purple: true,
        red: true,
        white: true,
        yellow: true,
        weeping_gala: true,
    },
    environmental: {
        willow: false,
        pine: true,
        plum: true,
        wisteria: true,
    },
    enderscape: {
        veiled: true,
        celestial: true,
        murublight: true,
    },
    atmospheric: {
        rosewood: true,
        morado: true,
        yucca: true,
        aspen: true,
        laurel: true,
        kousa: true,
        grimwood: true,
    },
    nomansland: {
        pine: true,
        maple: true,
        walnut: true,
        willow: true,
    },
    spawn: {
        rotten: true,
        date: true,
    },
    malum: {
        runewood: true,
        soulwood: true,
    },
    infernalexp: {
        luminous: true,
    },
    netherdescent: {
        wailing: true,
        embur: true,
        arisian: true,
        sythian: true,
    }
}
